In [95]:
import pandas as pd

In [96]:
# Import the CSV file and create a DataFrame.
player_df_final = pd.read_csv('player_df_final.csv')
player_df_final.head(10)

,ID,player,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
0,1,player1,1893.0,1251.8,97.8,63.0,33.900000,0.569,17.2,11.5,26.1,4.7,23.3,7.8,10.900000
1,2,player2,1386.0,1282.5,110.5,58.0,32.500000,0.511,24.8,9.7,26.9,6.1,0.9,10.7,27.300000
2,3,player3,1405.0,1252.3,105.8,55.0,36.300000,0.605,25.7,13.9,28.1,4.5,4.9,1.8,16.595759
3,4,player4,1282.0,1235.9,100.7,54.0,37.600000,0.636,29.5,11.0,22.3,4.8,4.6,5.6,22.350000
4,5,player5,1721.0,1254.0,105.7,59.0,30.500000,0.589,22.8,9.9,24.6,1.2,8.4,12.1,28.380000
5,6,player6,1004.0,1322.4,102.1,57.0,36.300000,0.574,20.3,13.5,31.0,1.2,20.5,3.4,9.830000
6,7,player7,1920.0,1207.6,109.8,55.0,37.000000,0.573,26.0,13.1,30.7,0.0,10.3,-2.6,8.710000
7,8,player8,1353.0,1348.1,112.2,57.0,35.208333,0.574,24.4,11.3,26.3,5.5,5.8,-2.2,8.717454
8,10,player10,1468.0,1400.9,93.7,61.0,35.600000,0.547,22.9,12.2,22.7,5.8,6.4,-2.9,3.115350
9,11,player11,1856.0,1303.8,93.4,55.0,33.600000,0.563,28.9,14.7,26.7,1.4,17.3,4.3,9.670000

In [97]:
# Create a DataFrame of only Tune Squad players.
ts_df  = player_df_final.iloc[26: , :]
ts_df

,ID,player,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
26,31,tune_squad1,2049.0,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000
27,32,tune_squad2,1795.0,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000
28,33,tune_squad3,1805.0,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000
29,34,tune_squad4,1743.0,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.853138
30,35,tune_squad5,1963.0,1539.1,117.4,59.771429,35.208333,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000
31,36,tune_squad6,2062.0,1505.7,111.5,59.771429,37.000000,0.620,29.8,15.6,36.2,4.9,23.9,14.7,27.860000
32,37,tune_squad7,1845.0,1435.7,113.1,69.000000,36.900000,0.634,33.2,14.0,36.5,4.1,21.5,16.4,34.260000
33,38,tune_squad8,1778.0,1526.4,109.3,66.000000,34.900000,0.612,30.6,15.9,35.9,5.5,18.8,13.7,28.650000
34,39,tune_squad9,1901.0,1444.1,109.7,67.000000,36.500000,0.609,27.2,14.8,35.5,5.0,21.8,8.9,20.120000
35,41,tune_squad11,2030.0,1431.0,112.3,68.000000,37.000000,0.618,32.5,15.3,34.5,5.7,15.7,13.2,30.070000
36,42,tune_squad12,1631.0,1465.7,110.1,66.000000,37.500000,0.613,28.4,14.4,35.7,6.5,20.7,14.0,28.400000
37,43,tune_squad13,1828.0,1507.2,112.7,64.000000,36.500000,0.618,31.3,14.0,34.9,5.9,21.3,14.5,29.094310
38,44,tune_squad14,1821.0,1443.7,118.8,66.000000,36.600000,0.609,27.3,13.5,35.8,7.0,23.8,11.5,22.960000
39,45,tune_squad15,1740.0,1443.9,114.1,68.000000,37.100000,0.611,26.6,15.2,29.3,8.3,17.7,11.1,21.220000
40,46,tune_squad16,1993.0,1459.0,112.5,59.771429,36.900000,0.627,30.4,15.0,33.7,6.3,19.3,14.1,28.760000

In [98]:
# Import Tune Squad player names.
ts_name_df = pd.read_csv('tune_squad.csv', sep='\t')
ts_name_df

    ID              player
0   31           Sylvester
1   32  Marvin the Martian
2   33         Road Runner
3   34     Foghorn Leghorn
4   35          Bugs Bunny
5   36          Elmer Fudd
6   37          Lola Bunny
7   38           Porky Pig
8   39     Tasmanian Devil
9   40        Yosemite Sam
10  41            Gossamer
11  42              Granny
12  43      Wile E. Coyote
13  44              Tweety
14  45            Penelope
15  46          Daffy Duck

In [99]:
# Merge the two DataFrames.
ts_df = pd.merge(ts_df, ts_name_df, on='ID', how='left', suffixes=('_type', '_name'))
ts_df.head()

,ID,player_type,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER,player_name
0,31,tune_squad1,2049.0,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000,Sylvester
1,32,tune_squad2,1795.0,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000,Marvin the Martian
2,33,tune_squad3,1805.0,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000,Road Runner
3,34,tune_squad4,1743.0,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.853138,Foghorn Leghorn
4,35,tune_squad5,1963.0,1539.1,117.4,59.771429,35.208333,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000,Bugs Bunny

In [100]:
# Rearrange the columns to put the ID and player_name columns next to each other.
column_list = list(ts_df)

player_name = column_list.pop()
column_list[1] = player_name

ts_df = ts_df[column_list]
ts_df.head()

,ID,player_name,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
0,31,Sylvester,2049.0,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000
1,32,Marvin the Martian,1795.0,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000
2,33,Road Runner,1805.0,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000
3,34,Foghorn Leghorn,1743.0,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.853138
4,35,Bugs Bunny,1963.0,1539.1,117.4,59.771429,35.208333,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000

In [101]:
# Create a list of only the column names we're interested in.
game_stat_cols = list(ts_df.iloc[:, 7:-1])
game_stat_stdevs = []

# game_stat_cols.remove('player')
# game_stat_cols.remove('player_name')
# Create a list of standard deviations for each stat.
for stat in game_stat_cols:
    # print(f"Kolumna {stat} ma typ danych: {ts_df[stat].dtype}")
    game_stat_stdevs.append(ts_df[stat].std())

# Create a Series of the standard deviations, with the stat names as the index.
stdev_s = pd.Series(game_stat_stdevs, index=game_stat_cols)
stdev_s

TS%     0.008262
AST     2.140494
TO      0.797197
USG     1.892718
ORR     1.139465
DRR     3.017962
REBR    1.802564
dtype: float64

In [102]:
# Import the models and libraries we need.
from sklearn.linear_model import LinearRegression
from numpy.random import randn

# Get the dependent and independent variables for modeling the PER.
# Get the dependent and independent variables for modeling the PER.
X = player_df_final.iloc[:, 7:-1].to_numpy()
y = player_df_final.iloc[:, -1]

In [103]:
# Define and fit the model.
lin_reg = LinearRegression()
lin_reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [104]:
# Print the player with the highest and lower PER for each iteration.
print('Iteration # \thigh PER \tlow PER')

# Run the simulation 10 times.
for i in range(10):

    # Define an empty temporary DataFrame for each iteration.
    # The columns of this DataFrame are the player stats and the index is the players' names.
    game_df = pd.DataFrame(columns=game_stat_cols, index=list(ts_df['player_name']))
    
    # Loop through each stat.
    for stat in game_stat_cols:
        
        # Each player's stats are used to generate a random value for each iteration.
        game_df[stat] = list(ts_df[stat] + randn(len(ts_df)) * stdev_s[stat])
    
    # Use the fitted model to predict players' PERs based on the randomized data.
    game_df['PER'] = lin_reg.predict(game_df)
    # Print the player with the highest and lower PER for each iteration.
    print('Iteration {}'.format(i+1) + ' \t' + game_df['PER'].idxmax() + ' \t' + game_df['PER'].idxmin())

Iteration # 	high PER 	low PER
Iteration 1 	Foghorn Leghorn 	Tasmanian Devil
Iteration 2 	Gossamer 	Penelope
Iteration 3 	Lola Bunny 	Tasmanian Devil
Iteration 4 	Porky Pig 	Tasmanian Devil
Iteration 5 	Lola Bunny 	Tweety
Iteration 6 	Lola Bunny 	Tweety
Iteration 7 	Lola Bunny 	Tasmanian Devil
Iteration 8 	Lola Bunny 	Road Runner
Iteration 9 	Lola Bunny 	Tasmanian Devil
Iteration 10 	Lola Bunny 	Penelope

In [108]:
# Initialize four empty DataFrames, one for each 12-minute period.
number_of_iterations = 4
df_list = [pd.DataFrame(columns=game_stat_cols, index = list(ts_df['player_name'])) for i in range(number_of_iterations)]
# For each period, generate randomized player data and predict the PER.
# Use the model fitted earlier.
for df in df_list:
    for stat in game_stat_cols:
        df[stat] = list(ts_df[stat] + randn(len(ts_df))* stdev_s[stat])
    df['PER'] = lin_reg.predict(df)

# Concatenate the DataFrames and make the players' names the index.
game_df = pd.concat(df_list)
game_df.rename_axis('player_name', inplace=True)

# Create another index for the period in question.
minutes = [(x // len(ts_df)) * 12 for x in range(len(game_df))]
game_df['minutes'] = minutes
game_df.set_index('minutes', append=True, inplace=True)
game_df = game_df.swaplevel()

game_df

                                 TS%        AST         TO        USG  \
minutes player_name
0       Sylvester           0.622736  35.556453  15.904478  34.710660
        Marvin the Martian  0.604801  29.699532  13.872893  33.442126
        Road Runner         0.609294  22.845012  13.287292  34.425032
        Foghorn Leghorn     0.616141  26.388442  14.690106  33.843393
        Bugs Bunny          0.640690  29.545298  16.409413  32.285957
        Elmer Fudd          0.619593  26.350883  15.651389  39.000714
        Lola Bunny          0.629438  33.254243  14.910221  38.731827
        Porky Pig           0.624758  26.119147  15.398284  34.537482
        Tasmanian Devil     0.604093  29.333013  13.515197  37.978331
        Gossamer            0.623047  30.871315  16.741186  34.940339
        Granny              0.627140  29.049251  14.229463  34.559398
        Wile E. Coyote      0.604769  32.090008  14.069749  36.509832
        Tweety              0.619449  26.101920  13.901731  35.320569
        Penelope            0.618050  25.027543  15.244867  28.247506
        Daffy Duck          0.624254  31.019266  16.403618  32.081828
12      Sylvester           0.613259  29.099759  15.676294  33.830133
        Marvin the Martian  0.616840  30.916760  15.031862  32.828899
        Road Runner         0.615799  27.778158  15.663547  34.552850
        Foghorn Leghorn     0.621413  31.838069  16.387037  33.114607
        Bugs Bunny          0.631925  35.398191  16.748246  33.348531
        Elmer Fudd          0.614460  28.143490  16.657900  36.588053
        Lola Bunny          0.638084  33.742061  15.454013  36.391024
        Porky Pig           0.606165  35.495726  16.140253  36.742403
        Tasmanian Devil     0.609299  28.719858  15.185795  31.624829
        Gossamer            0.621557  33.274746  14.332904  35.951200
        Granny              0.612970  30.165705  14.897840  34.405767
        Wile E. Coyote      0.613931  33.892979  13.717022  34.048134
        Tweety              0.587912  26.605760  13.679094  36.504587
        Penelope            0.614041  26.430416  15.095910  31.477056
        Daffy Duck          0.630830  31.044682  14.662856  35.014416
24      Sylvester           0.609626  32.672056  15.423150  34.690480
        Marvin the Martian  0.617703  30.180999  14.760250  32.301685
        Road Runner         0.614078  27.079869  14.434310  34.590991
        Foghorn Leghorn     0.618977  30.067293  15.553940  32.200516
        Bugs Bunny          0.627560  36.124566  16.329437  34.328767
        Elmer Fudd          0.627642  28.537059  15.777012  34.842347
        Lola Bunny          0.641456  33.738507  13.743819  36.661113
        Porky Pig           0.606721  31.093488  14.950330  36.640839
        Tasmanian Devil     0.606897  28.989561  14.244887  35.174865
        Gossamer            0.620333  35.517768  14.646202  35.194918
        Granny              0.625238  28.097111  14.642276  35.119374
        Wile E. Coyote      0.625152  29.440578  13.598880  35.790922
        Tweety              0.607340  27.400973  12.688622  36.459066
        Penelope            0.607490  27.413743  14.191425  31.383821
        Daffy Duck          0.619576  30.703241  15.746348  32.159593
36      Sylvester           0.608962  30.015897  16.206056  35.056887
        Marvin the Martian  0.622541  34.030581  13.009645  32.192219
        Road Runner         0.626489  25.468412  13.029357  36.699250
        Foghorn Leghorn     0.601775  29.376651  14.570771  33.321145
        Bugs Bunny          0.635394  30.721521  16.442475  29.822582
        Elmer Fudd          0.620165  29.639107  15.726808  35.171392
        Lola Bunny          0.639511  33.206934  13.159440  34.002685
        Porky Pig           0.612655  30.143252  14.547150  39.204373
        Tasmanian Devil     0.607535  27.082945  15.544966  36.834196
        Gossamer            0.603798  29.316107  14.709399  32.896197
        Granny              0.609809  29.471365  14.196497  34.225289
        Wile E. Coyote      0.625771  32.623836  13.734711  36.137794
        Tweety              0.600281  31.469145  13.569490  33.766456
        Penelope            0.616329  28.114787  15.231553  30.568660
        Daffy Duck          0.629563  28.785848  15.037976  31.422307

                                  ORR        DRR       REBR        PER
minutes player_name
0       Sylvester            5.902056  19.311482  12.741826  27.372425
        Marvin the Martian   7.997669  25.374878  11.901668  20.696631
        Road Runner          6.990444  27.977973  10.030123  17.235299
        Foghorn Leghorn      5.492947  16.920345  13.722720  29.196459
        Bugs Bunny           6.197059  18.577792  14.212626  28.492579
        Elmer Fudd           4.879248  21.907403  17.071593  33.657395
        Lola Bunny           2.825410  21.932729  18.185557  37.194419
        Porky Pig            6.477936  19.204715  13.691859  27.977453
        Tasmanian Devil      3.510235  17.297792   7.033532  22.908905
        Gossamer             5.525247  18.058741  15.952084  31.928352
        Granny               8.597717  14.365178  13.614079  31.422157
        Wile E. Coyote       3.777992  19.819829  15.794001  32.561344
        Tweety               7.318095  24.058248  11.516043  22.737127
        Penelope             9.140858  16.445451   8.035838  16.995316
        Daffy Duck           6.648074  23.322574  12.851944  22.641248
12      Sylvester            9.355471  21.273909  15.273842  27.229156
        Marvin the Martian   5.665223  26.657655  12.828651  21.567848
        Road Runner          6.696386  30.726214  11.890226  17.799456
        Foghorn Leghorn      5.174971  17.828074  15.099862  30.081540
        Bugs Bunny           7.153208  16.770842  12.615350  27.679149
        Elmer Fudd           4.963320  18.337842  16.929486  33.529163
        Lola Bunny           6.459513  22.559772  14.688699  29.875490
        Porky Pig            5.876650  14.761662  13.106477  30.839473
        Tasmanian Devil      5.944171  24.692893   6.654072  12.691567
        Gossamer             6.131609  16.036429  11.708824  29.235181
        Granny               6.580205  18.139312  16.827355  32.890142
        Wile E. Coyote       5.402140  23.211379  14.222746  27.292400
        Tweety               4.490550  20.030563  13.349591  27.573490
        Penelope             9.455598  11.767686   7.433663  20.905049
        Daffy Duck           7.567808  21.004288  12.814272  26.895892
24      Sylvester            7.570605  16.509823  11.032292  25.541305
        Marvin the Martian   6.175368  23.120814   8.869661  17.947248
        Road Runner          4.196037  30.224479  11.517855  18.760862
        Foghorn Leghorn      6.633693  18.696966  14.469836  27.905473
        Bugs Bunny           2.555090  19.848507  13.089873  28.228675
        Elmer Fudd           5.469483  18.067300  13.888919  29.582797
        Lola Bunny           2.730141  26.392464  19.512850  36.438579
        Porky Pig            6.126283  13.662557  16.538773  36.421633
        Tasmanian Devil      5.631711  21.650785   9.532250  21.189085
        Gossamer             5.816765  14.766618  10.149590  27.460096
        Granny               5.905562  22.026380  15.623758  30.045801
        Wile E. Coyote       5.864514  21.583054  13.412131  28.370581
        Tweety               5.963148  21.231922  11.356722  25.401636
        Penelope             8.062716  15.243788  11.154008  24.436404
        Daffy Duck           5.233523  18.215429  11.719796  24.703108
36      Sylvester            8.498910  19.755213  12.033000  24.171941
        Marvin the Martian   6.311475  26.678175  14.852223  25.575984
        Road Runner          7.160740  20.783523  11.182999  25.992460
        Foghorn Leghorn      7.060508  20.155159  13.857647  26.215627
        Bugs Bunny           6.838533  22.502211  15.081072  25.426156
        Elmer Fudd           5.743958  25.907916  12.765956  23.005847
        Lola Bunny           4.611902  27.181421  16.614812  30.024218
        Porky Pig            4.814158  20.519889  15.008002  32.382726
        Tasmanian Devil      7.009642  24.457274   5.912841  14.200343
        Gossamer             8.548532  13.047222  13.029161  28.872697
        Granny               6.153212  22.357395  14.454731  27.124695
        Wile E. Coyote       7.098975  19.032407  16.331109  34.173007
        Tweety               6.328744  27.670147  12.669466  21.039213
        Penelope            11.155303  22.564197  14.371121  23.096672
        Daffy Duck           4.932180  18.206532  14.379410  28.808569

In [ ]:
# Export the finished DataFrame to CSV.

game_df.to_csv('game_stats.csv')